# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: surendrakumar
# "service" is the name of this project. This will also be added to your AWS resource names.
service: key-logger-server

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  environment:
    BUCKET_NAME: tuivs-data
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: arn:aws:s3:::tuivs-data/*

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-offline
